config/routes.rb
Rails.application.routes.draw do
  get "likes/create"
  get "likes/destroy"
  root "static_pages#home"

  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    registrations: "users/registrations"
  }

  get "users/thanks", to: "static_pages#thanks", as: "user_thanks"

  resources :clients, only: [:show]

  resources :posts, except: [:index]

  resources :posts do
    resource :like, only: [:create, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :title, presence: true, uniqueness: { scope: :user_id }
  validates :text, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:show]
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def new
        @post = Post.new
    end
      
    def create
        @post = current_user.posts.build(post_params)    
        if @post.save
        redirect_to root_path, notice: "記事を作成しました！"
        else render :new end
    end

    def show
    end

    def edit
        redirect_to root_path unless @post.user == current_user
    end

    def update
        if @post.update(post_params)
            redirect_to root_path, notice: "記事を更新しました！"
        else render :edit end
    end
    
    def destroy
        @post = Post.find(params[:id])
        if @post.user == current_user
            @post.destroy
            redirect_to root_path, notice: "記事を削除しました！"
        else redirect_to root_path end
    end

    private
    
    def post_params
        params.require(:post).permit(:title, :text, :image)
    end

    def set_post
        @post = Post.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<% content_for :head do %>
  <style>
    textarea {
      width: 500px;
      height: 600px;
    }
  </style>
<% end %>

<% content_for :body do %>

<%= form_with(model: @post, local: true) do |f| %>
  <% if @post.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :text, "本文" %>
    <%= f.text_area :text %>
  </div>

  <div>
    <%= f.label :image, "扉絵" %>
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.submit "更新" %>
  </div>
<% end %>

<div style="margin-top: 20px;"><%= link_to '戻る', root_path %></div>

<% end %>

app/views/posts/new.html.erb
<% content_for :head do %>
  <style>
    textarea {
      width: 500px;
      height: 600px;
    }
  </style>
<% end %>


<% content_for :body do %>
<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, required: true %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, required: true %>
  </div>

  <div class="actions">
    <%= form.submit "Create Post" %>
  </div>
<% end %>

<div style="margin-top: 20px;"><%= link_to '戻る', root_path %></div>

<% end %>

app/views/posts/show.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag "article" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@200..900&family=Noto+Serif:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
<% end %>

<% content_for :body do %>
<h1><div><%= @post.title %></div></h1>

<section>
    <div class="container">
        <img src="<%= url_for(@post.image) %>" alt="扉絵">
        <div class="text">
            <p><%= @post.text %></p>
        </div>
    </div>
    <div  class="author">
        <p>作成者: <%= @post.user.name %></p>
        <p>投稿日: <%= @post.created_at.strftime('%Y-%m-%d %H:%M') %></p>
    </div>
    <div class="operation">
        <% if user_signed_in? %>
            <% if @post.user == current_user %>
                <%= link_to "編集", edit_post_path(@post.id) %>
                <%= form_with(url: post_path(@post.id), method: :delete) do %>
                    <button type="submit">削除<br><span style="font-size: 9px;">(アラート作ってないんですぐ削除されます)</span></button>
                <% end %>
            <% end %>
            <% if @post.liked_users.include?(current_user) %>
                <%= form_with(url: post_like_path(@post.id), method: :delete) do %>
                    <button type="submit">いいねを取り消す</button>
                <% end %>
            <% else %>
                <%= form_with(url: post_like_path(@post.id), method: :post) do %>
                    <button type="submit">いいねする</button>
                <% end %>
            <% end %>
        <% end %>
    <%= link_to '戻る', root_path %>
    </div>
</section>


<% end %>